trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

# Pull the SuiteCRM image from Docker Hub.
- script: |
    echo "Pulling the Bitnami SuiteCRM image..."
    docker pull $(bitnamiImage):$(tag)
  displayName: 'Pull Bitnami SuiteCRM Image'
  
# Tag the pulled image with our ACR repository name.
- script: |
    echo "Tagging image..."
    docker tag $(bitnamiImage):$(tag) $(registryPrefix)/$(imageRepositoryBitnami):$(tag)
  displayName: 'Tag Image'

# List docker images.
- script: docker images
  displayName: 'List Docker Images on Agent'

# Push Image to Container Registry.
- task: Docker@2
  displayName: Push Image to Dev Container Registry
  inputs:
    command: push
    repository: $(imageRepositoryBitnami)
    containerRegistry: $(dockerRegistryServiceConnectionDev)
    tags: |
      latest
      $(tag)
